/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)

#include "stdio.h"
#include "main.h"
#include "rtc.h"

// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x15)
#define ID_TEXT_0     (GUI_ID_USER + 0x16)
#define ID_BUTTON_0     (GUI_ID_USER + 0x17)
#define ID_TEXT_1     (GUI_ID_USER + 0x18)
#define ID_TEXT_2     (GUI_ID_USER + 0x19)
#define ID_TEXT_3     (GUI_ID_USER + 0x1A)
#define ID_DROPDOWN_0     (GUI_ID_USER + 0x1B)
#define ID_DROPDOWN_1     (GUI_ID_USER + 0x1C)
#define ID_DROPDOWN_2     (GUI_ID_USER + 0x1D)
#define ID_CHECKBOX_0     (GUI_ID_USER + 0x1F)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "SetAlarmWindow", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Alarm Setting", ID_TEXT_0, 5, 5, 120, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Quit", ID_BUTTON_0, 375, 10, 100, 50, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Hours", ID_TEXT_1, 5, 70, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Minutes", ID_TEXT_2, 140, 70, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Seconds", ID_TEXT_3, 275, 70, 80, 20, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Hours", ID_DROPDOWN_0, 45, 70, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Seconds", ID_DROPDOWN_1, 330, 70, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Minutes", ID_DROPDOWN_2, 190, 70, 80, 18, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 5, 100, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

extern WM_HWIN CreateWindow(void);

int alarm_hours;
int alarm_minutes;
int alarm_seconds;
int enable_alarm = 0;

void set_alarm_dropdown_time_init (WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  RTC_TimeTypeDef time;
  RTC_DateTypeDef date;

  HAL_RTC_GetTime(&hrtc, &time, RTC_FORMAT_BIN);
  HAL_RTC_GetDate(&hrtc, &date, RTC_FORMAT_BIN);

  // Init hours dropdown
  hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
  DROPDOWN_SetSel(hItem, time.Hours);
  alarm_hours = time.Hours;

  // Init minutes dropdown
  hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_2);
  DROPDOWN_SetSel(hItem, time.Minutes);
  alarm_minutes = time.Minutes;

  // Init seconds dropdown
  hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
  DROPDOWN_SetSel(hItem, time.Seconds);
  alarm_seconds = time.Seconds;
}

int is_alarm (void) {
  RTC_TimeTypeDef time;
  HAL_RTC_GetTime(&hrtc, &time, RTC_FORMAT_BIN);

  if (time.Hours == alarm_hours && time.Minutes == alarm_minutes && time.Seconds == alarm_seconds) {
    return 1;
  }
  return 0;
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Alarm Setting'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Quit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Hours'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Minutes'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Seconds'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "Enable");
    CHECKBOX_SetFont(hItem, GUI_FONT_16_1);
    // USER START (Optionally insert additional code for further widget initialization)

    char buffer[10];

    // Set hours dropdown
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_SetAutoScroll(hItem, 1);
    DROPDOWN_SetListHeight(hItem, 100);
    for (int i = 0; i < 24; i++) {
      sprintf(buffer, "%d", i);
      DROPDOWN_AddString(hItem, buffer);
    }

    // Set minutes dropdown
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
    DROPDOWN_SetAutoScroll(hItem, 1);
    DROPDOWN_SetListHeight(hItem, 100);
    for (int i = 0; i < 60; i++) {
      sprintf(buffer, "%d", i);
      DROPDOWN_AddString(hItem, buffer);
    }

    // // Set seconds dropdown
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_2);
    DROPDOWN_SetAutoScroll(hItem, 1);
    DROPDOWN_SetListHeight(hItem, 100);
    for (int i = 0; i < 60; i++) {
      sprintf(buffer, "%d", i);
      DROPDOWN_AddString(hItem, buffer);
    }

    set_alarm_dropdown_time_init(pMsg);

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Quit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_DeleteWindow(pMsg->hWin);
        CreateWindow();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_0: // Notifications sent by 'Hours'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
        alarm_hours = DROPDOWN_GetSel(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_1: // Notifications sent by 'Seconds'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
        alarm_seconds = DROPDOWN_GetSel(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_2: // Notifications sent by 'Minutes'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_2);
        alarm_minutes = DROPDOWN_GetSel(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_0: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
        enable_alarm = CHECKBOX_GetState(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSetAlarmWindow
*/
WM_HWIN CreateSetAlarmWindow(void);
WM_HWIN CreateSetAlarmWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
