/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)

#include "stdio.h"
#include "main.h"
#include "rtc.h"

// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_TEXT_0     (GUI_ID_USER + 0x01)
#define ID_BUTTON_0     (GUI_ID_USER + 0x02)
#define ID_TEXT_1     (GUI_ID_USER + 0x03)
#define ID_TEXT_2     (GUI_ID_USER + 0x04)
#define ID_TEXT_3     (GUI_ID_USER + 0x05)
#define ID_DROPDOWN_0     (GUI_ID_USER + 0x06)
#define ID_DROPDOWN_1     (GUI_ID_USER + 0x07)
#define ID_DROPDOWN_2     (GUI_ID_USER + 0x08)
#define ID_LISTBOX_0     (GUI_ID_USER + 0x0A)
#define ID_TEXT_4     (GUI_ID_USER + 0x0B)
#define ID_BUTTON_1     (GUI_ID_USER + 0x0C)
#define ID_BUTTON_2     (GUI_ID_USER + 0x0D)
#define ID_BUTTON_3     (GUI_ID_USER + 0x0E)


// USER START (Optionally insert additional defines)

#define MAX_ALARM_NUM 5
#define ALARM_ENABLE 1
#define ALARM_DISABLE 0
#define NO_ALARM 2
#define CHANGE_ALARM_STATE 0
#define ADD_NEW_ALARM 1

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "SetAlarmWindow", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Alarm Setting", ID_TEXT_0, 5, 5, 120, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Quit", ID_BUTTON_0, 375, 10, 100, 50, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Hours", ID_TEXT_1, 5, 70, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Minutes", ID_TEXT_2, 140, 70, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Seconds", ID_TEXT_3, 275, 70, 80, 20, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Hours", ID_DROPDOWN_0, 45, 70, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Seconds", ID_DROPDOWN_1, 330, 70, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Minutes", ID_DROPDOWN_2, 190, 70, 80, 18, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 70, 160, 120, 100, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "alarm list", ID_TEXT_4, 5, 160, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Enable", ID_BUTTON_1, 5, 100, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Disable", ID_BUTTON_2, 115, 100, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Delete", ID_BUTTON_3, 225, 100, 80, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

extern WM_HWIN CreateWindow(void);

int alarm_hours[MAX_ALARM_NUM];
int alarm_minutes[MAX_ALARM_NUM];
int alarm_seconds[MAX_ALARM_NUM];
int enable_alarm[MAX_ALARM_NUM] = {NO_ALARM, NO_ALARM, NO_ALARM, NO_ALARM, NO_ALARM};
int alarm_num = 0;
int alarm_index = 0;
int enable_way = ADD_NEW_ALARM;

void dropdown_time_init (WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  RTC_TimeTypeDef time;
  RTC_DateTypeDef date;

  HAL_RTC_GetTime(&hrtc, &time, RTC_FORMAT_BIN);
  HAL_RTC_GetDate(&hrtc, &date, RTC_FORMAT_BIN);

  // Init hours dropdown
  hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
  DROPDOWN_SetSel(hItem, time.Hours);

  // Init minutes dropdown
  hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_2);
  DROPDOWN_SetSel(hItem, time.Minutes);

  // Init seconds dropdown
  hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
  DROPDOWN_SetSel(hItem, time.Seconds);
}

void alarm_list_init (WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);

  char alarm_time[25];
  for (int i = 0; i < alarm_num; i++) {
    if (enable_alarm[i] == ALARM_ENABLE) {
      sprintf(alarm_time, "%02d:%02d:%02d enable", alarm_hours[i], alarm_minutes[i], alarm_seconds[i]);
      LISTBOX_AddString(hItem, alarm_time);
    }
    else if (enable_alarm[i] == ALARM_DISABLE) {
      sprintf(alarm_time, "%02d:%02d:%02d disable", alarm_hours[i], alarm_minutes[i], alarm_seconds[i]);
      LISTBOX_AddString(hItem, alarm_time);
    }
  }
}

int is_alarm (void) {
  RTC_TimeTypeDef time;
  RTC_DateTypeDef date;
  HAL_RTC_GetTime(&hrtc, &time, RTC_FORMAT_BIN);
  HAL_RTC_GetDate(&hrtc, &date, RTC_FORMAT_BIN);

  for (int i = 0; i < alarm_num; i++) {
    if (time.Hours == alarm_hours[i] && time.Minutes == alarm_minutes[i] && time.Seconds == alarm_seconds[i] && enable_alarm[i] == ALARM_ENABLE) {
      return 1;
    }
  }

  return 0;
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Alarm Setting'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Quit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Hours'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Minutes'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Seconds'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'alarm list'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Enable'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Disable'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Delete'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    // USER START (Optionally insert additional code for further widget initialization)

    char buffer[10];

    // Set hours dropdown
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_SetAutoScroll(hItem, 1);
    DROPDOWN_SetListHeight(hItem, 100);
    for (int i = 0; i < 24; i++) {
      sprintf(buffer, "%d", i);
      DROPDOWN_AddString(hItem, buffer);
    }

    // Set minutes dropdown
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
    DROPDOWN_SetAutoScroll(hItem, 1);
    DROPDOWN_SetListHeight(hItem, 100);
    for (int i = 0; i < 60; i++) {
      sprintf(buffer, "%d", i);
      DROPDOWN_AddString(hItem, buffer);
    }

    // // Set seconds dropdown
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_2);
    DROPDOWN_SetAutoScroll(hItem, 1);
    DROPDOWN_SetListHeight(hItem, 100);
    for (int i = 0; i < 60; i++) {
      sprintf(buffer, "%d", i);
      DROPDOWN_AddString(hItem, buffer);
    }

    dropdown_time_init(pMsg);
    alarm_list_init(pMsg);

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Quit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_DeleteWindow(pMsg->hWin);
        CreateWindow();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_0: // Notifications sent by 'Hours'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        enable_way = ADD_NEW_ALARM;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        enable_way = ADD_NEW_ALARM;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_1: // Notifications sent by 'Seconds'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        enable_way = ADD_NEW_ALARM;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        enable_way = ADD_NEW_ALARM;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_2: // Notifications sent by 'Minutes'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        enable_way = ADD_NEW_ALARM;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        enable_way = ADD_NEW_ALARM;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
        alarm_index = LISTBOX_GetSel(hItem);
        enable_way = CHANGE_ALARM_STATE;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Enable'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        if (enable_way == ADD_NEW_ALARM) {
          hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
          alarm_hours[alarm_num] = DROPDOWN_GetSel(hItem);
          hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
          alarm_seconds[alarm_num] = DROPDOWN_GetSel(hItem);
          hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_2);
          alarm_minutes[alarm_num] = DROPDOWN_GetSel(hItem);

          enable_alarm[alarm_num] = ALARM_ENABLE;

          char alarm_time[25];
          sprintf(alarm_time, "%02d:%02d:%02d enable", alarm_hours[alarm_num], alarm_minutes[alarm_num], alarm_seconds[alarm_num]);
          hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
          LISTBOX_AddString(hItem, alarm_time);

          if (alarm_num < MAX_ALARM_NUM) {
            alarm_num++;
          }
        }
        else if (enable_way == CHANGE_ALARM_STATE) {
          enable_alarm[alarm_index] = ALARM_ENABLE;
          hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
          char alarm_time[25];
          sprintf(alarm_time, "%02d:%02d:%02d enable", alarm_hours[alarm_index], alarm_minutes[alarm_index], alarm_seconds[alarm_index]);
          LISTBOX_SetString(hItem, alarm_time, alarm_index);
        }
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Disable'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        enable_alarm[alarm_index] = ALARM_DISABLE;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
        char alarm_time[25];
        sprintf(alarm_time, "%02d:%02d:%02d disable", alarm_hours[alarm_index], alarm_minutes[alarm_index], alarm_seconds[alarm_index]);
        LISTBOX_SetString(hItem, alarm_time, alarm_index);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Delete'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
        LISTBOX_DeleteItem(hItem, alarm_index);
        for (int i = alarm_index; i < alarm_num - 1; i++) {
          alarm_hours[i] = alarm_hours[i + 1];
          alarm_minutes[i] = alarm_minutes[i + 1];
          alarm_seconds[i] = alarm_seconds[i + 1];
          enable_alarm[i] = enable_alarm[i + 1];
        }
        alarm_num--;
        enable_alarm[alarm_num] = NO_ALARM;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSetAlarmWindow
*/
WM_HWIN CreateSetAlarmWindow(void);
WM_HWIN CreateSetAlarmWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
