/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)

#include "main.h"
#include "adc.h"

// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x07)
#define ID_GRAPH_0     (GUI_ID_USER + 0x08)
#define ID_BUTTON_0     (GUI_ID_USER + 0x09)


// USER START (Optionally insert additional defines)

#define TIME_DOMAIN 0
#define FREQUENCE_DOMAIN 1

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "ShowWaveSignalWindow", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 20, 10, 440, 200, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Quit", ID_BUTTON_0, 190, 215, 100, 50, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

uint8_t is_adc_ok = 0;
WM_HWIN hTimeDomainGraph;

extern WM_HWIN CreateWaveSignalWindow(void);

extern uint8_t domain;

void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef* hadc) {
  if (hadc->Instance == ADC3) {
    is_adc_ok = 1;
  }
}

// void update_time_domain_graph (WM_HWIN hGraph) {
//   if (is_adc_ok) {
//     GRAPH_DATA_Handle hData = GRAPH_DATA_YT_Create(GUI_DARKGREEN, ADC_BUFFER_SIZE + 1, adc_buffer, ADC_BUFFER_SIZE);
//     GRAPH_AttachData(hGraph, hData);
//     GRAPH_DATA_YT_Delete(hData);
//     is_adc_ok = 0;
//   }
// }

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Quit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    // USER START (Optionally insert additional code for further widget initialization)

    hTimeDomainGraph = hItem;

    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    GRAPH_SetGridVis(hItem, 1);  // Grid is visual

    // if (domain == TIME_DOMAIN) {

    // }
    // else if (domain == FREQUENCE_DOMAIN) {

    // }

    is_adc_ok = 0;
    HAL_ADC_Start_DMA(&hadc3, (uint32_t*)adc_buffer, ADC_BUFFER_SIZE);

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Quit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        HAL_ADC_Stop_DMA(&hadc3);
        WM_DeleteWindow(pMsg->hWin);
        CreateWaveSignalWindow();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateShowWaveSignalWindow
*/
WM_HWIN CreateShowWaveSignalWindow(void);
WM_HWIN CreateShowWaveSignalWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
