/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)

#include "main.h"
#include "rtc.h"
#include "stdio.h"
#include "ffconf.h"
#include "ff.h"
#include "ff_gen_drv.h"
#include "diskio.h"
#include "string.h"

// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0             (GUI_ID_USER + 0x00)
#define ID_TEXT_0             (GUI_ID_USER + 0x01)
#define ID_TEXT_1             (GUI_ID_USER + 0x02)
#define ID_TEXT_2             (GUI_ID_USER + 0x03)
#define ID_BUTTON_0             (GUI_ID_USER + 0x04)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 1, 1, 480, 272, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "00:00:00", ID_TEXT_0, 200, 140, 80, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0000/00/00", ID_TEXT_1, 190, 100, 100, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "WeekDay", ID_TEXT_2, 185, 180, 110, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Settings", ID_BUTTON_0, 375, 10, 100, 50, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

extern WM_HWIN CreateSettingsWindow(void);
extern WM_HWIN CreateAlarmWindow(void);
extern int is_alarm (void);

extern int enable_alarm;

// static const char root_dir[] = "";  // The root dir of TF card
// static const char chinese_font_36_addr[] = "Font/ChineseFont36.xbf";
// static const char chinese_font_20_addr[] = "Font/ChineseFont20.xbf";
// GUI_XBF_DATA ChineseFont_36_XBF;
// GUI_FONT ChineseFont_36;
// GUI_XBF_DATA ChineseFont_20_XBF;
// GUI_FONT ChineseFont_20;
// extern const char* settings;

// // fatfs
// uint8_t fatfs_init_flag = 0;
// FATFS fs;
// FIL fp;
// UINT bytes_read;

// char files[20][50];
// uint8_t count;

void update_date (WM_MESSAGE * pMsg) {
  WM_HWIN time_item = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
  WM_HWIN date_item = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
  WM_HWIN weekday_item = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);

  RTC_DateTypeDef date;
  RTC_TimeTypeDef time;
  char time_str[10];
  char date_str[12];
  char weekday_str[11];

  HAL_RTC_GetTime(&hrtc, &time, RTC_FORMAT_BIN);
  HAL_RTC_GetDate(&hrtc, &date, RTC_FORMAT_BIN);
  sprintf(time_str, "%02d:%02d:%02d", time.Hours, time.Minutes, time.Seconds);
  sprintf(date_str, "%04d/%02d/%02d", (2000 + date.Year), date.Month, date.Date);
  switch (date.WeekDay) {
    case RTC_WEEKDAY_MONDAY:
      sprintf(weekday_str, "Monday");
      break;
    case RTC_WEEKDAY_TUESDAY:
      sprintf(weekday_str, "Tuesday");
      break;
    case RTC_WEEKDAY_WEDNESDAY:
      sprintf(weekday_str, "Wednesday");
      break;
    case RTC_WEEKDAY_THURSDAY:
      sprintf(weekday_str, "Thursday");
      break;
    case RTC_WEEKDAY_FRIDAY:
      sprintf(weekday_str, "Friday");
      break;
    case RTC_WEEKDAY_SATURDAY:
      sprintf(weekday_str, "Saturday");
      break;
    case RTC_WEEKDAY_SUNDAY:
      sprintf(weekday_str, "Sunday");
      break;
    default:
      break;
  }

  TEXT_SetText(time_item, time_str);
  TEXT_SetText(date_item, date_str);
  TEXT_SetText(weekday_item, weekday_str);
}

// static int _cb_Font_XBF_GetData (U32 offset, U16 num_bytes, void* pVoid, void* pBuffer) {
//   FRESULT res;

//   if (fatfs_init_flag == 0) {
//     res = f_mount(&fs, (const TCHAR*)root_dir, 1);
//     fatfs_init_flag = 1;
//   }

//   res = f_open(&fp, (const TCHAR*)pVoid, FA_OPEN_EXISTING | FA_READ);
//   if (res == FR_OK) {
//     f_lseek(&fp, offset);
//     res = f_read(&fp, pBuffer, num_bytes, &bytes_read);
//     f_close(&fp);
//     return 1;
//   }
//   else {
//     return 0;
//   }
// }

// void create_xbf_font (void) {
//   GUI_XBF_CreateFont(&ChineseFont_20, 
//                      &ChineseFont_20_XBF, 
//                      GUI_XBF_TYPE_PROP_AA2_EXT, 
//                      _cb_Font_XBF_GetData, 
//                      (void*)chinese_font_20_addr);
// }

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of '00:00:00'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '0000/00/00'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'WeekDay'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Settings'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    // USER START (Optionally insert additional code for further widget initialization)

    WM_CreateTimer(pMsg->hWin, 0, 1000, 0);
    update_date(pMsg);

    // hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    // BUTTON_SetText(hItem, settings);
    // BUTTON_SetFont(hItem, &ChineseFont_20);

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Settings'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_DeleteWindow(pMsg->hWin);
        CreateSettingsWindow();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_TIMER:
    update_date(pMsg);
    WM_RestartTimer(pMsg->Data.v, 1000);
    if (is_alarm() && enable_alarm) {
      WM_DeleteWindow(pMsg->hWin);
      CreateAlarmWindow();
    }
    break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
